#!/bin/bash
export ANDROID_SDK_HOME="$WANGHUA_ANDROID_BASE/android-sdk" 
export ANDROID_HOME="$ANDROID_SDK_HOME" 
export PATH="$ANDROID_SDK_HOME/tools":$PATH
alias myandroidsdk="cd $ANDROID_SDK_HOME"
