#!/bin/bash
#export M2_HOME="$MY_JAVA_BASE/apache-maven-3.3.1"
export M2_HOME="/usr/local/Cellar/maven/3.3.1/libexec"
export PATH="$M2_HOME/bin":$PATH
#export M2_USER_HOME="$MY_JAVA_BASE/m2_user_home"
export MAVEN_OPTS="-DdownloadSources=true -DdownloadJavadocs=true"
